#!/usr/bin/env bash
# Converts glTF locomotion clips to ozz files the client can load (Linux/macOS).
#
#   tools/convert_animations.sh <source dir> [output dir (default assets/anim)] [path to gltf2ozz]
#
# See tools/convert_animations.ps1 and assets/anim/README.md.

set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
src="$(cd "$1" && pwd)"
out="${2:-$root/assets/anim}"
mkdir -p "$out"
out="$(cd "$out" && pwd)"
tool="${3:-$(find "${HOME}/.cache/cinderbox-build" -path '*/bin/gltf2ozz' -type f 2>/dev/null | head -1)}"
[[ -x "$tool" ]] || { echo "gltf2ozz not found; build the project first or pass its path"; exit 1; }
echo "using $tool"

clips=(idle walk run jump_start fall land)
declare -A sources
for clip in "${clips[@]}"; do
	for ext in glb gltf; do
		if [[ -f "$src/$clip.$ext" ]]; then sources[$clip]="$src/$clip.$ext"; break; fi
	done
done
[[ ${#sources[@]} -gt 0 ]] || { echo "no clip files in $src"; exit 1; }

cfg_json="$(mktemp)"
run_tool() {
	printf '%s' "$2" > "$cfg_json"
	"$tool" "--file=$1" "--config_file=$cfg_json" "--log_level=standard"
}

for clip in "${clips[@]}"; do
	if [[ -n "${sources[$clip]:-}" ]]; then first="$clip"; break; fi
done
echo "== skeleton from ${sources[$first]}"
run_tool "${sources[$first]}" "{ \"skeleton\": { \"filename\": \"$out/skeleton.ozz\", \"import\": { \"enable\": true } }, \"animations\": [] }"

{
	echo "# generated by tools/convert_animations.sh"
	echo "skeleton = skeleton.ozz"
} > "$out/anim.cfg"
for clip in "${clips[@]}"; do
	if [[ -z "${sources[$clip]:-}" ]]; then echo "== $clip: no source file, skipped"; continue; fi
	echo "== $clip"
	run_tool "${sources[$clip]}" "{ \"skeleton\": { \"filename\": \"$out/skeleton.ozz\", \"import\": { \"enable\": false } }, \"animations\": [ { \"clip\": \"*\", \"filename\": \"$out/$clip.ozz\" } ] }"
	echo "$clip = $clip.ozz" >> "$out/anim.cfg"
done
{
	echo "# scale = 0.01        # omit to auto-detect centimetre rigs"
	echo "lock_root_xz = true   # ignore horizontal root motion (clips not exported 'In Place')"
} >> "$out/anim.cfg"
rm -f "$cfg_json"
echo "wrote $out/anim.cfg - preview with: cb_client --anim-viewer --assets \"$out\""
