# Converts glTF locomotion clips to ozz files the client can load.
#
#   powershell -ExecutionPolicy Bypass -File tools\convert_animations.ps1 -Source <dir> [-Output assets\anim]
#
# <dir> contains one file per clip, named idle, walk, run, jump_start, fall, land (.glb or .gltf).
# Missing clips are skipped (the client shows the rest pose for them). The skeleton is taken from
# the first clip found. See assets/anim/README.md for exporting Mixamo clips from Blender.

param(
	[Parameter(Mandatory = $true)][string]$Source,
	[string]$Output = "",
	[string]$Gltf2ozz = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
if (-not $Output) { $Output = Join-Path $root "assets\anim" }
$Source = (Resolve-Path $Source).Path
New-Item -ItemType Directory -Force $Output | Out-Null
$Output = (Resolve-Path $Output).Path

if (-not $Gltf2ozz) {
	$found = Get-ChildItem -Path (Join-Path $env:LOCALAPPDATA "cinderbox-build") -Filter gltf2ozz.exe -Recurse -ErrorAction SilentlyContinue |
		Where-Object { $_.DirectoryName -like "*\bin" } | Select-Object -First 1
	if (-not $found) { throw "gltf2ozz.exe not found; build the project first or pass -Gltf2ozz" }
	$Gltf2ozz = $found.FullName
}
Write-Host "using $Gltf2ozz"

$clips = @("idle", "walk", "run", "jump_start", "fall", "land")
$sources = @{}
foreach ($clip in $clips) {
	foreach ($ext in @(".glb", ".gltf")) {
		$path = Join-Path $Source ($clip + $ext)
		if (Test-Path $path) { $sources[$clip] = $path; break }
	}
}
if ($sources.Count -eq 0) { throw "no clip files (idle/walk/run/jump_start/fall/land .glb/.gltf) in $Source" }

function Fwd([string]$p) { return $p -replace "\\", "/" }

function Run-Gltf2ozz([string]$file, [string]$config) {
	$cfgPath = Join-Path $env:TEMP "cinderbox_gltf2ozz.json"
	Set-Content -Path $cfgPath -Value $config -Encoding ascii
	& $Gltf2ozz "--file=$file" "--config_file=$cfgPath" "--log_level=standard"
	if ($LASTEXITCODE -ne 0) { throw "gltf2ozz failed on $file" }
}

$skeleton = Fwd (Join-Path $Output "skeleton.ozz")
$first = $clips | Where-Object { $sources.ContainsKey($_) } | Select-Object -First 1
Write-Host "== skeleton from $($sources[$first])"
Run-Gltf2ozz $sources[$first] "{ `"skeleton`": { `"filename`": `"$skeleton`", `"import`": { `"enable`": true } }, `"animations`": [] }"

$cfg = @("# generated by tools/convert_animations.ps1", "skeleton = skeleton.ozz")
foreach ($clip in $clips) {
	if (-not $sources.ContainsKey($clip)) {
		Write-Host "== $clip`: no source file, skipped" -ForegroundColor Yellow
		continue
	}
	$out = Fwd (Join-Path $Output "$clip.ozz")
	Write-Host "== $clip"
	# One clip per file is expected; "*" picks it up whatever the exporter named it.
	Run-Gltf2ozz $sources[$clip] "{ `"skeleton`": { `"filename`": `"$skeleton`", `"import`": { `"enable`": false } }, `"animations`": [ { `"clip`": `"*`", `"filename`": `"$out`" } ] }"
	$cfg += "$clip = $clip.ozz"
}
$cfg += "# scale = 0.01        # omit to auto-detect centimetre rigs"
$cfg += "lock_root_xz = true   # ignore horizontal root motion (clips not exported 'In Place')"
Set-Content -Path (Join-Path $Output "anim.cfg") -Value $cfg -Encoding ascii
Write-Host "wrote $Output\anim.cfg - preview with: cb_client --anim-viewer --assets `"$Output`"" -ForegroundColor Green
